create table if not exists public.player_match_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('practice', '1v1')),
  outcome text not null check (outcome in ('session', 'win', 'loss', 'draw')),
  score integer not null default 0,
  opponent_score integer,
  rounds integer,
  accuracy_pct integer,
  best_time integer,
  best_streak integer,
  created_at timestamptz not null default now()
);

create index if not exists player_match_history_user_created_idx
on public.player_match_history (user_id, created_at desc);

alter table public.player_match_history enable row level security;

drop policy if exists "player_match_history_owner_access" on public.player_match_history;
create policy "player_match_history_owner_access"
on public.player_match_history
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

grant select, insert on table public.player_match_history to authenticated;
grant usage, select on sequence public.player_match_history_id_seq to authenticated;
